### PR TITLE
New signature for constrained_parafac function

### PR DESCRIPTION
**Pull request by caglayantuna**
After our discussion in PR [284](https://github.com/tensorly/tensorly/pull/284), I created a constrained_parafac_new file with `initialize_constraints_and_parameters` function which does not exist in the PR and `constrained_parafac_new` function which has larger signature compared to `constrained_parafac` in the PR. Besides, I have added a notebook in order to show how `initialize_constraints_and_parameters` works. As your suggestion, these functions may have different kind of inputs (float, list or dictionary) for constraints. If we agree with the new signature, I will improve the doc accordingly and add these functions to PR. 

I imported required libraries directly from tensorly in order to run notebook easily. I hope, this way is what you expect from lab repository.

### CODE REVIEW

**Comment by JeanKossaifi** [comment]
Thanks @caglayantuna -- I do prefer this API, I think it's also less error prone and reduces the number of arguments (e.g. l1_reg directly contains information on the modes that are regularized as well as the regularization parameter). If we go for this we may as well integrate it directly in the main function rather than having it as a wrapper on top, this will save some computation and avoid having to do string operations for each constraint.

**Comment by caglayantuna** [comment]
Thanks for your comment @JeanKossaifi . Regarding your suggestion, this wrapper includes almost 200 lines because of the several if conditions. I think, main function may seem sloppy if I integrate them, right? If it is not important,  I will update the PR soon.

**Comment by JeanKossaifi** [comment]
I think conversion / verification will exist regardless, e.g. in tensorly/tenalg/proximal.py. 
The interface with explicit names seems to me less error-prone to end-users and more discoverable through auto-complete, hence my preference for it. However, if others feel strongly otherwise I'm also happy to go with the string based version :)

**Comment by JeanKossaifi** [comment]
Should we close this as the main feature has been merged?

**Comment by caglayantuna** [comment]
Yes, closing.

**Pull request closed without merging**
